"""HTML report generation using Jinja2."""

from __future__ import annotations

from datetime import date
from decimal import Decimal
from pathlib import Path
from typing import Any

from jinja2 import Template

from traderharness.metrics.performance import PerformanceMetrics

_REPORT_TEMPLATE = """<!DOCTYPE html>
<html>
<head><title>FinHarness Report - {{ agent_name }}</title>
<style>
body { font-family: -apple-system, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; }
h1 { color: #1a1a2e; }
table { border-collapse: collapse; width: 100%; margin: 20px 0; }
th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
th { background: #f4f4f4; }
.positive { color: #16a34a; }
.negative { color: #dc2626; }
.chart { margin: 20px 0; padding: 10px; background: #fafafa; border-radius: 8px; }
</style></head>
<body>
<h1>{{ agent_name }} — Backtest Report</h1>
<p>Period: {{ start_date }} to {{ end_date }} ({{ metrics.trading_days }} trading days)</p>

<h2>Performance Summary</h2>
<table>
<tr><th>Metric</th><th>Value</th></tr>
<tr><td>Total Return</td><td class="{{ 'positive' if metrics.total_return_pct > 0 else 'negative' }}">{{ metrics.total_return_pct }}%</td></tr>
<tr><td>Annual Return</td><td>{{ metrics.annual_return_pct }}%</td></tr>
<tr><td>Sharpe Ratio</td><td>{{ metrics.sharpe_ratio }}</td></tr>
<tr><td>Sortino Ratio</td><td>{{ metrics.sortino_ratio }}</td></tr>
<tr><td>Calmar Ratio</td><td>{{ metrics.calmar_ratio }}</td></tr>
<tr><td>Max Drawdown</td><td class="negative">-{{ metrics.max_drawdown_pct }}%</td></tr>
<tr><td>Max Consecutive Loss Days</td><td>{{ metrics.max_consecutive_loss_days }}</td></tr>
<tr><td>Win Rate</td><td>{{ metrics.win_rate }}%</td></tr>
<tr><td>Profit/Loss Ratio</td><td>{{ metrics.profit_loss_ratio }}</td></tr>
<tr><td>Turnover Rate (annualized)</td><td>{{ metrics.turnover_rate }}</td></tr>
<tr><td>Total Trades</td><td>{{ metrics.total_trades }}</td></tr>
<tr><td>Final Value</td><td>¥{{ "{:,.2f}".format(metrics.final_value) }}</td></tr>
</table>

{% if monthly_returns %}
<h2>Monthly Returns</h2>
<div class="chart">
{% for month, ret in monthly_returns %}
<span style="display:inline-block;width:60px">{{ month }}</span>
<span class="{{ 'positive' if ret > 0 else 'negative' }}">{{ "%.1f"|format(ret) }}%</span><br>
{% endfor %}
</div>
{% endif %}

<p><em>Generated by FinHarness v0.1.0</em></p>
</body></html>"""


def generate_html_report(
    agent_name: str,
    metrics: PerformanceMetrics,
    equity_curve: list[tuple[date, Decimal]],
    start_date: date,
    end_date: date,
    trades: list[dict] | None = None,
) -> str:
    """Generate an HTML report string."""
    monthly_returns = _calc_monthly_returns(equity_curve)
    template = Template(_REPORT_TEMPLATE)
    return template.render(
        agent_name=agent_name,
        metrics=metrics,
        start_date=start_date,
        end_date=end_date,
        monthly_returns=monthly_returns,
    )


def save_html_report(html: str, path: str | Path) -> Path:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(html, encoding="utf-8")
    return p


def _calc_monthly_returns(
    equity_curve: list[tuple[date, Decimal]],
) -> list[tuple[str, float]]:
    if len(equity_curve) < 2:
        return []
    monthly: dict[str, tuple[float, float]] = {}
    for d, v in equity_curve:
        key = d.strftime("%Y-%m")
        val = float(v)
        if key not in monthly:
            monthly[key] = (val, val)
        else:
            monthly[key] = (monthly[key][0], val)
    results = []
    for month, (start_val, end_val) in monthly.items():
        if start_val > 0:
            ret = (end_val - start_val) / start_val * 100
            results.append((month, round(ret, 1)))
    return results
