"""Build, verify, and install the public full-market dataset release."""

from __future__ import annotations

import hashlib
import json
import os
import shutil
from collections.abc import Callable
from pathlib import Path
from typing import Any

import pandas as pd

FULL_DATASET_REPO = "ANTICH/traderharness-ashare-5y"


class DatasetIntegrityError(RuntimeError):
    """Raised when a downloaded or staged dataset fails verification."""


def build_public_news(source: pd.DataFrame) -> pd.DataFrame:
    """Return a schema-compatible release without redistributing CLS正文."""
    public = source.copy()
    titles = public.get("title", pd.Series("", index=public.index)).fillna("").astype(str)
    has_title = titles.str.strip().ne("")
    public["content"] = titles.where(has_title, "快讯正文未随公开数据集分发。")
    public["content_source"] = has_title.map({True: "derived_headline", False: "redacted"})
    return public


def build_dataset_card() -> str:
    """Return the Hugging Face dataset card for the verified public bundle."""
    return """---
pretty_name: TraderHarness A-share 5-Year Market Dataset
language:
- zh
license: other
task_categories:
- time-series-forecasting
- reinforcement-learning
tags:
- finance
- quantitative-trading
- a-share
- market-data
- llm-agents
- backtesting
- synthetic-data
size_categories:
- 100M<n<1B
---

# TraderHarness A-share 5-year dataset

Point-in-time market data for evaluating and training autonomous LLM trading agents with
[TraderHarness](https://github.com/HephaestLab/TraderHarness).

## Contents

- Full-market daily OHLCV
- 284,219,844 canonical 5-minute bars partitioned by year
- Announcement titles, policy news, fundamentals, valuation, dividends, and CSI 300
- Entity templates used by TraderHarness's deterministic runtime company mask
- SHA-256 release manifest for verified, atomic installation

Install the complete release:

```bash
pip install "traderharness[data]"
traderharness data download --full
```

## Derived and redacted fields

Public news content contains entity-templated headlines or explicit redaction notices only.
Licensed CLS full text is not redistributed. Announcement data contains titles rather than source
documents. Runtime pseudo-identities are generated by TraderHarness and are not stored as a single
fixed mapping in this release.

## Intended use

Historical research, agent evaluation, trajectory generation, and reproducible backtesting.
This dataset does not provide investment advice and is not intended for live order routing.

## Licensing and provenance

Compiled from the maintainers' personal research archive and freely available public internet
sources. For research use only. No warranty. Upstream data rights remain with their owners and may
differ by field, provider, and jurisdiction. Review the project data documentation and upstream
terms before redistribution or commercial use.
"""


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(8 * 1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def verify_manifest(root: str | Path) -> dict[str, Any]:
    """Verify every release file against manifest size and SHA-256."""
    release_root = Path(root)
    manifest_path = release_root / "manifest.json"
    if not manifest_path.exists():
        raise DatasetIntegrityError("Dataset manifest.json is missing")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest.get("schema_version") != 1:
        raise DatasetIntegrityError("Unsupported dataset manifest schema")
    for entry in manifest.get("files", []):
        relative = Path(entry["path"])
        if relative.is_absolute() or ".." in relative.parts:
            raise DatasetIntegrityError(f"Unsafe manifest path: {relative}")
        path = release_root / relative
        if not path.is_file():
            raise DatasetIntegrityError(f"Dataset file is missing: {relative}")
        if path.stat().st_size != int(entry["bytes"]):
            raise DatasetIntegrityError(f"Dataset file size mismatch: {relative}")
        if _sha256(path) != entry["sha256"]:
            raise DatasetIntegrityError(f"Dataset checksum mismatch: {relative}")
    return manifest


def download_full_dataset(
    target: str | Path,
    *,
    force: bool = False,
    repo_id: str = FULL_DATASET_REPO,
    snapshot_downloader: Callable[..., str] | None = None,
) -> Path:
    """Download, verify, then atomically install the full dataset."""
    destination = Path(target)
    if destination.exists() and not force:
        raise FileExistsError(
            f"Dataset directory already exists: {destination}. Pass --force to replace it."
        )
    staging = destination.with_name(destination.name + ".download")
    backup = destination.with_name(destination.name + ".backup")
    if staging.exists():
        shutil.rmtree(staging)
    staging.parent.mkdir(parents=True, exist_ok=True)

    if snapshot_downloader is None:
        try:
            from huggingface_hub import snapshot_download
        except ImportError as exc:
            raise ImportError("huggingface_hub is required. Install traderharness[data].") from exc
        snapshot_downloader = snapshot_download

    snapshot_downloader(
        repo_id=repo_id,
        local_dir=str(staging),
        repo_type="dataset",
    )
    verify_manifest(staging)

    if backup.exists():
        shutil.rmtree(backup)
    try:
        if destination.exists():
            destination.replace(backup)
        staging.replace(destination)
    except Exception:
        if not destination.exists() and backup.exists():
            backup.replace(destination)
        raise
    if backup.exists():
        shutil.rmtree(backup)
    return destination


def _link_or_copy(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    try:
        os.link(source, destination)
    except OSError:
        shutil.copy2(source, destination)


def build_release(
    source_dir: str | Path,
    output_dir: str | Path,
    *,
    force: bool = False,
) -> dict[str, Any]:
    """Build an atomic public release from canonical local data."""
    source = Path(source_dir)
    output = Path(output_dir)
    if output.exists() and not force:
        raise FileExistsError(f"Release directory already exists: {output}")
    staging = output.with_name(output.name + ".building")
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir(parents=True)

    direct_files = {
        "daily.parquet": "daily.parquet",
        "fundamentals.parquet": "fundamentals.parquet",
        "business_segments.parquet": "business_segments.parquet",
        "dividends.parquet": "dividends.parquet",
        "valuation.parquet": "valuation.parquet",
        "index_300.parquet": "index_300.parquet",
        "metadata.json": "metadata.json",
        "announcements_templated.parquet": "announcements.parquet",
    }
    for source_name, release_name in direct_files.items():
        path = source / source_name
        if not path.is_file():
            raise FileNotFoundError(f"Required canonical dataset is missing: {path}")
        _link_or_copy(path, staging / release_name)

    min5_root = source / "5min_clean"
    min5_files = sorted(min5_root.glob("year=*/*.parquet"))
    if not min5_files:
        raise FileNotFoundError(f"Canonical 5-minute partitions are missing: {min5_root}")
    for path in min5_files:
        _link_or_copy(path, staging / path.relative_to(source))

    news_source = source / "news_cls_templated.parquet"
    if not news_source.is_file():
        raise FileNotFoundError(f"Templated news dataset is missing: {news_source}")
    build_public_news(pd.read_parquet(news_source)).to_parquet(
        staging / "news_cls.parquet",
        index=False,
        compression="zstd",
    )

    (staging / "README.md").write_text(build_dataset_card(), encoding="utf-8")

    files = []
    for path in sorted(item for item in staging.rglob("*") if item.is_file()):
        relative = path.relative_to(staging).as_posix()
        files.append(
            {
                "path": relative,
                "bytes": path.stat().st_size,
                "sha256": _sha256(path),
            }
        )
    manifest = {
        "schema_version": 1,
        "repo_id": FULL_DATASET_REPO,
        "files": files,
        "total_bytes": sum(item["bytes"] for item in files),
        "news_policy": "entity-templated headlines; original content redacted",
    }
    (staging / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    verify_manifest(staging)

    if output.exists():
        shutil.rmtree(output)
    staging.replace(output)
    return manifest
